Benchmark = bitcount

SRCDIR = src
SRCSUFFIX = c

CFLAGS = -std=c90
CINCLUDE = -I.

LDFLAGS = -lm
WASMFLAGS = -D_WASI_EMULATED_PROCESS_CLOCKS -lwasi-emulated-process-clocks

include ../../../Makefile.in
