Benchmark = blowfish

SRCDIR = ./src
SRCSUFFIX = c

CFLAGS = -fomit-frame-pointer -std=c89 -include stdlib.h -include ctype.h -include unistd.h
CINCLUDE =
OPT = -O2
LDFLAGS =

include ../../../Makefile.in
